/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Skin evaluation result containing possible condition and its confidence level in JSON format
 *
 * @param condition 
 * @param confidence 
 */


data class SkinEvaluationResult (

    @Json(name = "condition")
    val condition: kotlin.String,

    @Json(name = "confidence")
    val confidence: java.math.BigDecimal

)

